### ISSUE TITLE
Cloud API Keys working with Akash Network.

### ISSUE THREAD

**Issue by evanmcfarland** [AlexandriaDAO/core#30]
Currently, api keys cannot communicate with Akash hosted docker containers. The issue is unknown though likely related to cors.

This is an essential feature because it is the cheapest way to host instances and it caps the expenditures in case the keys are leaked.

Along with this completion, we need to add basic instructions for users who'd like to host on Akash.

**Comment by zeeghazi** [comment]
I did some testing with a custom instance on akash, I wasn't able to reproduce auth/cors related issues, so will be closing this for now. 

The instructions will be added with the UI soon as well

This is the build script thats working for me 

<pre>
---
version: "2.0"
services:
  meilisearch:
    image: getmeili/meilisearch
    expose:
      - port: 7700
        as: 80
        to:
          - global: true
    env:
      - MEILI_MASTER_KEY=MEILI_KEY
profiles:
  compute:
    meilisearch:
      resources:
        cpu:
          units: 1
        memory:
          size: 1Gi
        storage:
          - size: 5Gi
  placement:
    dcloud:
      pricing:
        meilisearch:
          denom: uakt
          amount: 10000
deployment:
  meilisearch:
    dcloud:
      profile: meilisearch
      count: 1

</pre>

**Comment by zeeghazi** [comment]
I did some testing with a custom instance on akash, I wasn't able to reproduce auth/cors related issues, so will be closing this for now. 

The instructions will be added with the UI soon as well

This is the build script thats working for me 

<pre>
---
version: "2.0"
services:
  meilisearch:
    image: getmeili/meilisearch
    expose:
      - port: 7700
        as: 80
        to:
          - global: true
    env:
      - MEILI_MASTER_KEY=MEILI_KEY
profiles:
  compute:
    meilisearch:
      resources:
        cpu:
          units: 1
        memory:
          size: 1Gi
        storage:
          - size: 5Gi
  placement:
    dcloud:
      pricing:
        meilisearch:
          denom: uakt
          amount: 10000
deployment:
  meilisearch:
    dcloud:
      profile: meilisearch
      count: 1

</pre>
